"""Initial schema

Revision ID: 78ab4d9e831a
Revises: 
Create Date: 2026-08-19 08:30:56.088857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78ab4d9e831a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_request_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('api_name', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('quota_cost', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('request_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_logs_requested_at', 'api_request_logs', ['requested_at'], unique=False)
    op.create_table('channels',
    sa.Column('channel_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subscriber_count', sa.BigInteger(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_table('concepts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('search_queries', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('concept_daily_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('signal_date', sa.Date(), nullable=False),
    sa.Column('population_size', sa.Integer(), nullable=False),
    sa.Column('observation_coverage', sa.Float(), nullable=False),
    sa.Column('median_view_velocity', sa.Float(), nullable=True),
    sa.Column('median_view_growth', sa.Float(), nullable=True),
    sa.Column('median_view_acceleration', sa.Float(), nullable=True),
    sa.Column('median_normalized_velocity', sa.Float(), nullable=True),
    sa.Column('median_reach_ratio', sa.Float(), nullable=True),
    sa.Column('median_interaction_density', sa.Float(), nullable=True),
    sa.Column('p25_velocity', sa.Float(), nullable=True),
    sa.Column('p75_velocity', sa.Float(), nullable=True),
    sa.Column('velocity_std', sa.Float(), nullable=True),
    sa.Column('big_creator_signal', sa.Float(), nullable=True),
    sa.Column('medium_creator_signal', sa.Float(), nullable=True),
    sa.Column('small_creator_signal', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_id', 'signal_date', name='uq_concept_id_signal_date')
    )
    op.create_index('idx_concept_signals_concept_date', 'concept_daily_signals', ['concept_id', 'signal_date'], unique=False)
    op.create_table('search_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_before', sa.DateTime(timezone=True), nullable=True),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('requested_limit', sa.Integer(), nullable=False),
    sa.Column('returned_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('video_id', sa.String(length=255), nullable=False),
    sa.Column('channel_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('first_discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_index('idx_videos_channel_id', 'videos', ['channel_id'], unique=False)
    op.create_table('population_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('search_run_id', sa.Integer(), nullable=False),
    sa.Column('target_size', sa.Integer(), nullable=False),
    sa.Column('actual_size', sa.Integer(), nullable=False),
    sa.Column('selection_strategy', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_run_id'], ['search_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_run_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=255), nullable=False),
    sa.Column('semantic_score', sa.Float(), nullable=True),
    sa.Column('language_score', sa.Float(), nullable=True),
    sa.Column('metadata_score', sa.Float(), nullable=True),
    sa.Column('creator_size_bucket', sa.String(length=50), nullable=True),
    sa.Column('selection_status', sa.String(length=50), nullable=False),
    sa.Column('selection_rank', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_run_id'], ['search_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_video_candidates_search_run_id', 'video_candidates', ['search_run_id'], unique=False)
    op.create_table('video_observations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.String(length=255), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('view_count', sa.BigInteger(), nullable=False),
    sa.Column('like_count', sa.BigInteger(), nullable=True),
    sa.Column('comment_count', sa.BigInteger(), nullable=True),
    sa.Column('subscriber_count', sa.BigInteger(), nullable=True),
    sa.Column('video_age_seconds', sa.BigInteger(), nullable=True),
    sa.Column('api_source', sa.String(length=50), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'observed_at', name='uq_video_id_observed_at')
    )
    op.create_index('idx_video_obs_observed_at', 'video_observations', ['observed_at'], unique=False)
    op.create_index('idx_video_obs_video_observed', 'video_observations', ['video_id', 'observed_at'], unique=False)
    op.create_table('population_members',
    sa.Column('population_run_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=255), nullable=False),
    sa.Column('creator_size_bucket', sa.String(length=50), nullable=False),
    sa.Column('selection_score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('selected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['population_run_id'], ['population_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('population_run_id', 'video_id')
    )
    op.create_index('idx_population_members_run_id', 'population_members', ['population_run_id'], unique=False)
    op.create_table('video_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.String(length=255), nullable=False),
    sa.Column('observation_id', sa.BigInteger(), nullable=False),
    sa.Column('age_days', sa.Float(), nullable=True),
    sa.Column('views_per_day', sa.Float(), nullable=True),
    sa.Column('view_velocity', sa.Float(), nullable=True),
    sa.Column('view_growth', sa.Float(), nullable=True),
    sa.Column('view_acceleration', sa.Float(), nullable=True),
    sa.Column('views_per_subscriber', sa.Float(), nullable=True),
    sa.Column('normalized_velocity', sa.Float(), nullable=True),
    sa.Column('reach_ratio', sa.Float(), nullable=True),
    sa.Column('interaction_density', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['video_observations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_metrics')
    op.drop_index('idx_population_members_run_id', table_name='population_members')
    op.drop_table('population_members')
    op.drop_index('idx_video_obs_video_observed', table_name='video_observations')
    op.drop_index('idx_video_obs_observed_at', table_name='video_observations')
    op.drop_table('video_observations')
    op.drop_index('idx_video_candidates_search_run_id', table_name='video_candidates')
    op.drop_table('video_candidates')
    op.drop_table('population_runs')
    op.drop_index('idx_videos_channel_id', table_name='videos')
    op.drop_table('videos')
    op.drop_table('search_runs')
    op.drop_index('idx_concept_signals_concept_date', table_name='concept_daily_signals')
    op.drop_table('concept_daily_signals')
    op.drop_table('concepts')
    op.drop_table('channels')
    op.drop_index('idx_api_logs_requested_at', table_name='api_request_logs')
    op.drop_table('api_request_logs')
    # ### end Alembic commands ###
